name: Release Manager Action
description: GitHub Action to tag and release a new version of your project
author: 'ragdata'
inputs:
    version:
        description: "Release version"
        required: false
    type:
        description: "Bump Type (patch/minor/major)"
        required: false

runs:
    using: docker
    image: Dockerfile

branding:
    icon: package
    color: red
