name: Release Manager Action
description: GitHub Action to tag and release a new version of your project
author: 'ragdata'
inputs:
    version:
        description: "Release version"
        required: false
    type:
        description: "Bump Type (auto/patch/minor/major/first/version)"
        required: false
    branch:
        description: "Branch to create release from"
        required: false
    pre-release:
        description: "Mark as pre-release?"
        required: false

runs:
    using: docker
    image: Dockerfile

branding:
    icon: package
    color: red
