extends: .release.base.yml
name: ${GITHUB_REPOSITORY}
# description:
version: ${CURRENT_VERSION}
# copyright:
# website:
repo_url: https://github.com/${GITHUB_REPOSITORY}
authors:
    - username: ${GITHUB_ACTOR}
      # first_name:
      # surname:
      email: ${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com
      # affiliation:
protect_prod: true
changelog: true
