name: {{ name }}
version: {{ version }}
repository:
    label: {{ repository.label }}
    url: {{ repository.url }}
authors:
    - username: {{ github.actor }}
      email: {{ github.actor.id }}+{{ github.actor }}@users.noreply.github.com
git:
    user:
        name: {{ github.actor }}
        email: {{ github.actor.id }}+{{ github.actor }}@users.noreply.github.com
    branches:
        prod: {{ github.ref }}
        patch: hotfix/.*
        release: release/.*
    message:
        release: "build(release): release version {{ version }}"
rules:
    protect_prod: true
categories:
    types:
        - type: build
          title: Builds
          description: Changes that affect the build system or external dependencies
          icon: 🔨
        - type: chore
          title: Chores
          description: Other changes that don't modify src or test files
          icon: ♻️
        - type: ci
          title: Continuous Integration
          description: Changes to our CI configuration files and scripts
          icon: ⚙️
        - type: docs
          title: Documentation
          description: Changes to documentation only
          icon: 📘
        - type: feat
          title: Features
          description: A new feature
          icon: ✨
        - type: fix
          title: Bug Fixes
          description: Changes which fix problems with the project
          icon: 🐞
        - type: perf
          title: Performance Improvements
          description: Code changes which improve performance
          icon: 🚀
        - type: refactor
          title: Code Refactoring
          description: A code change that neither fixes a bug nor adds a new feature
          icon: 📦
        - type: revert
          title: Reversions
          description: Reverting to a previous commit
          icon: 💫
        - type: style
          title: Styles
          description: Cosmetic changes which don't affect the meaning of the code
          icon: 💎
        - type: test
          title: Tests
          description: Changes to unit tests or other testing code
          icon: 🚨
    aliases:
        - type: initial
          link: feat
          title: Initial Commits
          description: The first files committed to the repository - usually generic
          icon: 🎉
        - type: dependencies
          link: fix
          title: Dependencies
          description: Software libraries (often supplied by third-parties) upon which our software's functionality depends
          icon: ⏫
        - type: devDependencies
          link: chore
          title: Dev Dependencies
          description: Software libraries upon which we depend in order to develop our software
          icon: 🔼
        - type: metadata
          link: fix
          title: Metadata
          description: Files which store information about our software
          icon: 📀
    logged:
        - feat
        - fix
        - perf
        - style
        - docs
